### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by AmmarTariq10** [MinesNicaicai/janus-webrtc-react-native#1]
Hi,
I was able to successfully run this project with link of official meetecho demo, I was unable to access your server repo, moreover I could not start call in metecho demo url I was stuck at getUserMedia. Please guide me how to more a head.
Thank you

**Comment by li-yanhao** [comment]
Hi,
This project is deployed using another repo https://github.com/MinesNicaicai/janus-demo-docker . You can give it a try. 
But if you have problem with getUserMedia, I cannot help with this. You may have to look up the doc of WebRTC. This project does not aim at communication between two mobile peers. It is for streaming from a mobile streamer to a server (e.g. Nginx in my case).
