### ISSUE TITLE
chatroom & AudioBridge

### ISSUE THREAD

**Issue by Namec** [MinesNicaicai/janus-webrtc-react-native#2]
Hello,

can i use this to implemente audiobridge and the chatroom plugin ??

best

**Comment by li-yanhao** [comment]
> Hello,
> 
> can i use this to implemente audiobridge and the chatroom plugin ??
> 
> best

Hi,

Sure you can add audiobridge and chatroom plugins following the Janus demos. You can adapt the janus.js of the Janus web demo to your react-native use. Then check the corresponding APIs (https://janus.conf.meetecho.com/docs/audiobridge.html, https://janus.conf.meetecho.com/docs/videoroom.html) 
on the plugin docs, change the [back-end](https://github.com/MinesNicaicai/janus-webrtc-backend) and [janus config](https://github.com/MinesNicaicai/janus-webrtc-gateway-docker) for your proper demands.

In fact I decomposed the sub-functions from janus videoroom demo and built this demo for one-to-one video chat use. So can you.

best
